<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE Profiles[
  <!ELEMENT Profiles (chara*)>
  <!ATTLIST chara id CDATA #REQUIRED>
  <!ELEMENT chara (Name, DisplayName, Description, Nation, DefHP, MaxHP, DefBaseAP, MaxBaseAP)>
  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT DisplayName (#PCDATA)>
  <!ELEMENT Description (#PCDATA)>
  <!ELEMENT Nation (#PCDATA)>
  <!ELEMENT DefHP (#PCDATA)>
  <!ELEMENT MaxHP (#PCDATA)>
  <!ELEMENT DefBaseAP (#PCDATA)>
  <!ELEMENT MaxBaseAP (#PCDATA)>
]>

<Profiles>
  <chara id="1">
    <Name><![CDATA[IriminaAndreche]]></Name>
    <DisplayName>
      イリミナ・アンドレーチェ
    </DisplayName>
    <Description>
      イエーブンのアンドレーチェ大公。
    </Description>
    <Nation>
      イエーブン
    </Nation>
    <DefHP>
      1000
    </DefHP>
    <MaxHP>
      20000
    </MaxHP>
    <DefBaseAP>
      100
    </DefBaseAP>
    <MaxBaseAP>
      8000
    </MaxBaseAP>
  </chara>
</Profiles>